### ISSUE TITLE
Roadmap for 2022

### ISSUE THREAD

**Issue by TomokoMiyake** [kintone-labs/kintone-ui-component#936]
This is our product roadmap for 2022.
We would like to share it with contributors and users.
It will only cover big themes, but of course, we will improve existing components and consider developing new components based on users' requests.

# Future components planned to release
- [ ] 🏃 Mobile Date/Time series
- [ ] 🤔 Desktop Table and ReadOnlyTable
  - We are now considering Table for edit and ReadOnlyTable for read.
- [ ] 🤔 Next new components consideration (Attachment, Tab, FieldGroup, etc)

# Development Theme
- [ ] 🏃 Sharing coding way with React/Vue *unofficial
  - We provided React version on the v0 series. But we don't have a plan to release it on v1. So for existing React and additionally Vue users, we want to share the coding way with them. Note that this will not be the official way and use it at your own risk.
- [ ] 🏃 Avoid conflicting with other versions defined in plugin/app
  - There is a version conflict issue when defining multiple kintone UI Component packages on app/plugin at the same time. So we are working on solving the issue now.
- [ ] 🤔 Custom CSS
  - We are planning to provide the Custom CSS way to make it possible to arrange the design of the component officially.

# Other
- [ ] Stop maintenance of v0 series when completing almost components on v1
  - v0 series is now on maintenance mode (only bug fix and package update), but we will stop maintaining it within this year to focus on developing the mainstream v1 series. About after releasing v1's high priority components/themes (Mobile Date/Time series, Desktop Table series, React/Vue coding way). We will announce beforehand if we decide when.

🏃: work in progress
🤔: under discussion
✋: postpone

*Note that we might change the content in the future.
